### PR TITLE
Update Cargo.toml to match version on crates.io

### PR DESCRIPTION
**Pull request by aidanhs**
(wasn't bumped when 0.1.3 was released)

### CODE REVIEW

**Comment by aidanhs** [comment]
@homu r+

**Comment by kbknapp** [comment]
@homu r+

**Comment by kbknapp** [comment]
Strange...

**Comment by kbknapp** [comment]
Once the DB error is fixed I should be able to add you. For now I'll just remove the homu required gate so you can merge manually

**Comment by aidanhs** [comment]
Thanks!

**Pull request merged**
