### PR TITLE
fix: make response::Droplet's fields public

### PR DESCRIPTION
**Pull request by yberreby**
this allows the user to query the ID, the droplet name, and other useful
information.

### CODE REVIEW

**Comment by kbknapp** [comment]
Once you're satisfied with a PR you can comment `@homu r+` then homu will do a merge check and merge the PR and close any applicable issues. 

Well issues that are listed in the commit messages  such as Closes #18

**Comment by yberreby** [comment]
@kbknapp Thanks for the tip, I haven't used homu much :)

I was actually waiting for my `rustc` to update so I could investigate the failed build. Unless you're OK with it not working on the latest nightly, since it's a dependency problem anyway.

**Comment by yberreby** [comment]
@yo-bot r+

**Comment by yberreby** [comment]
@homu r+

**Comment by yberreby** [comment]
@kbknapp See - `aster` is broken on the latest nightly, so it won't let me merge. Since the master branch is equally broken, is there a way to the override the CI checks?

**Comment by kbknapp** [comment]
@yberreby, I've temporarily set it to not require checks to merge.

**Pull request merged**
