### PR TITLE
Use the appropriate method when performing a request

### PR DESCRIPTION
**Pull request by aidanhs**
This fixes droplet creation

### CODE REVIEW

**Comment by kbknapp** [comment]
@aidanhs since I haven't had a ton of time to work on this crate, if you'd like I can make you a collaborator on this project which would give you push/merge access and @homu access. Let me know if you're interested.

**Comment by kbknapp** [comment]
@homu r+

**Comment by aidanhs** [comment]
@kbknapp I'm up for that.

**Comment by kbknapp** [comment]
Excellent! I've added you as a collaborator, and I'll add you to @homu once I get home. Feel free to push your branches to this repo instead of a your fork if you'd like. Once I add you to homu you'll be able to use that to merge as well.

**Comment by aidanhs** [comment]
Great, thanks!

**Comment by aidanhs** [comment]
Oh, and could you push a new version of doapi-rs to crates.io when you get home as well? Just while you've got doapi on your mind :)

**Comment by kbknapp** [comment]
Will do!

**Comment by kbknapp** [comment]
@aidanhs you've been added.

**Pull request merged**
